builtin_agents:
  chart_agent:
    module: app.agents.plugins.chart_agent
    class_name: ChartAgent
  general_assistant:
    module: app.agents.plugins.general_assistant
    class_name: GeneralAssistantAgent
  document_qa:
    module: app.agents.plugins.document_qa
    class_name: DocumentQaAgent
  task_execution:
    module: app.agents.plugins.task_execution_agent
    class_name: TaskExecutionAgent
  tool_using:
    module: app.agents.plugins.tool_using
    class_name: ToolUsingAgent
  project_agent:
    module: app.agents.plugins.project_agent
    class_name: ProjectAgent
  memory_curator:
    module: app.agents.plugins.memory_curator
    class_name: MemoryCuratorAgent
  reviewer:
    module: app.agents.plugins.reviewer
    class_name: ReviewerAgent