"""Canonical runtime catalog of backend trace event names."""

from __future__ import annotations

from app.contracts.trace import (
    AGENT_COMPLETED,
    AGENT_SELECTED,
    AGENT_STARTED,
    CONTEXT_CREATED,
    DOCUMENT_INGEST_COMPLETED,
    DOCUMENT_INGEST_FAILED,
    DOCUMENT_INGEST_STARTED,
    ERROR_OCCURRED,
    LLM_CALL_COMPLETED,
    LLM_CALL_FAILED,
    LLM_CALL_STARTED,
    LLM_FALLBACK_SELECTED,
    LLM_POLICY_CHECKED,
    LLM_PROFILE_RESOLVED,
    LLM_PROVIDER_HEALTH_CHECKED,
    LLM_RETRY_SCHEDULED,
    LLM_STREAM_CANCELLED,
    LLM_STREAM_COMPLETED,
    LLM_STREAM_STARTED,
    MEMORY_DELETE_BY_SCOPE_COMPLETED,
    MEMORY_DELETE_BY_SCOPE_FAILED,
    MEMORY_DELETE_BY_SCOPE_STARTED,
    MEMORY_EXPORT_BY_SCOPE_COMPLETED,
    MEMORY_EXPORT_BY_SCOPE_FAILED,
    MEMORY_GET_COMPLETED,
    MEMORY_GET_FAILED,
    MEMORY_GET_STARTED,
    MEMORY_HEALTH_CHECKED,
    MEMORY_LIFECYCLE_UPDATED,
    MEMORY_SEARCH_COMPLETED,
    MEMORY_SEARCH_FAILED,
    MEMORY_SEARCH_STARTED,
    MEMORY_STATS_CHECKED,
    MEMORY_WRITE_COMPLETED,
    MEMORY_WRITE_FAILED,
    MEMORY_WRITE_STARTED,
    MINIMUM_TRACE_EVENT_TYPES,
    REQUEST_RECEIVED,
    RESPONSE_RETURNED,
    STRATEGY_SELECTED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_FAILED,
    TOOL_CALL_STARTED,
    WORKFLOW_STATE_LOADED,
    WORKFLOW_STATE_SAVED,
)

__all__ = (
    "AGENT_COMPLETED",
    "AGENT_SELECTED",
    "AGENT_STARTED",
    "CONTEXT_CREATED",
    "DOCUMENT_INGEST_COMPLETED",
    "DOCUMENT_INGEST_FAILED",
    "DOCUMENT_INGEST_STARTED",
    "ERROR_OCCURRED",
    "LLM_CALL_COMPLETED",
    "LLM_CALL_FAILED",
    "LLM_CALL_STARTED",
    "LLM_FALLBACK_SELECTED",
    "LLM_POLICY_CHECKED",
    "LLM_PROFILE_RESOLVED",
    "LLM_PROVIDER_HEALTH_CHECKED",
    "LLM_RETRY_SCHEDULED",
    "LLM_STREAM_CANCELLED",
    "LLM_STREAM_COMPLETED",
    "LLM_STREAM_STARTED",
    "MEMORY_DELETE_BY_SCOPE_COMPLETED",
    "MEMORY_DELETE_BY_SCOPE_FAILED",
    "MEMORY_DELETE_BY_SCOPE_STARTED",
    "MEMORY_EXPORT_BY_SCOPE_COMPLETED",
    "MEMORY_EXPORT_BY_SCOPE_FAILED",
    "MEMORY_GET_COMPLETED",
    "MEMORY_GET_FAILED",
    "MEMORY_GET_STARTED",
    "MEMORY_HEALTH_CHECKED",
    "MEMORY_LIFECYCLE_UPDATED",
    "MEMORY_SEARCH_COMPLETED",
    "MEMORY_SEARCH_FAILED",
    "MEMORY_SEARCH_STARTED",
    "MEMORY_STATS_CHECKED",
    "MEMORY_WRITE_COMPLETED",
    "MEMORY_WRITE_FAILED",
    "MEMORY_WRITE_STARTED",
    "MINIMUM_TRACE_EVENT_TYPES",
    "REQUEST_RECEIVED",
    "RESPONSE_RETURNED",
    "STRATEGY_SELECTED",
    "TOOL_CALL_COMPLETED",
    "TOOL_CALL_FAILED",
    "TOOL_CALL_STARTED",
    "WORKFLOW_STATE_LOADED",
    "WORKFLOW_STATE_SAVED",
    "STARTUP_STARTED",
    "STARTUP_COMPLETED",
    "STARTUP_FAILED",
    "CONFIG_LOADED",
    "CONFIG_VALIDATION_FAILED",
    "HEALTH_CHECKED",
    "POLICY_EVALUATED",
    "POLICY_DENIED",
    "SESSION_CREATED",
    "SESSION_RESUMED",
    "SESSION_RESET",
    "STREAM_STARTED",
    "STREAM_COMPLETED",
    "STREAM_CANCELLED",
    "STREAM_FAILED",
    "MCP_TOOLS_LISTED",
    "MCP_CALL_STARTED",
    "MCP_CALL_COMPLETED",
    "MCP_CALL_FAILED",
    "MEMORY_UPSERT_STARTED",
    "MEMORY_UPSERT_COMPLETED",
    "MEMORY_UPSERT_FAILED",
    "WORKFLOW_STATE_RESET",
    "WORKFLOW_STATE_CONFLICT",
    "ADDITIONAL_TRACE_EVENT_TYPES",
    "ALL_TRACE_EVENT_TYPES",
)

STARTUP_STARTED = "startup_started"
STARTUP_COMPLETED = "startup_completed"
STARTUP_FAILED = "startup_failed"
CONFIG_LOADED = "config_loaded"
CONFIG_VALIDATION_FAILED = "config_validation_failed"
HEALTH_CHECKED = "health_checked"
POLICY_EVALUATED = "policy_evaluated"
POLICY_DENIED = "policy_denied"
SESSION_CREATED = "session_created"
SESSION_RESUMED = "session_resumed"
SESSION_RESET = "session_reset"
STREAM_STARTED = "stream_started"
STREAM_COMPLETED = "stream_completed"
STREAM_CANCELLED = "stream_cancelled"
STREAM_FAILED = "stream_failed"
MCP_TOOLS_LISTED = "mcp_tools_listed"
MCP_CALL_STARTED = "mcp_call_started"
MCP_CALL_COMPLETED = "mcp_call_completed"
MCP_CALL_FAILED = "mcp_call_failed"
MEMORY_UPSERT_STARTED = "memory_upsert_started"
MEMORY_UPSERT_COMPLETED = "memory_upsert_completed"
MEMORY_UPSERT_FAILED = "memory_upsert_failed"
WORKFLOW_STATE_RESET = "workflow_state_reset"
WORKFLOW_STATE_CONFLICT = "workflow_state_conflict"

ADDITIONAL_TRACE_EVENT_TYPES = (
    STARTUP_STARTED,
    STARTUP_COMPLETED,
    STARTUP_FAILED,
    CONFIG_LOADED,
    CONFIG_VALIDATION_FAILED,
    HEALTH_CHECKED,
    POLICY_EVALUATED,
    POLICY_DENIED,
    SESSION_CREATED,
    SESSION_RESUMED,
    SESSION_RESET,
    STREAM_STARTED,
    STREAM_COMPLETED,
    STREAM_CANCELLED,
    STREAM_FAILED,
    MCP_TOOLS_LISTED,
    MCP_CALL_STARTED,
    MCP_CALL_COMPLETED,
    MCP_CALL_FAILED,
    MEMORY_UPSERT_STARTED,
    MEMORY_UPSERT_COMPLETED,
    MEMORY_UPSERT_FAILED,
    WORKFLOW_STATE_RESET,
    WORKFLOW_STATE_CONFLICT,
)

ALL_TRACE_EVENT_TYPES = MINIMUM_TRACE_EVENT_TYPES + ADDITIONAL_TRACE_EVENT_TYPES
