"""Public orchestration package surface."""

from __future__ import annotations

from importlib import import_module
from typing import Any


_LAZY_EXPORTS = {
	"AgentExecutionError": ("app.orchestration.errors", "AgentExecutionError"),
	"AgentNotFoundError": ("app.orchestration.errors", "AgentNotFoundError"),
	"CitationSummary": ("app.orchestration.models", "CitationSummary"),
	"ConversationMessage": ("app.orchestration.models", "ConversationMessage"),
	"DefaultOrchestrationRuntime": ("app.orchestration.core", "DefaultOrchestrationRuntime"),
	"DirectAgentOrchestrationRuntime": ("app.orchestration.core", "DirectAgentOrchestrationRuntime"),
	"EchoOrchestrationRuntime": ("app.orchestration.core", "EchoOrchestrationRuntime"),
	"MemorySearchSummary": ("app.orchestration.models", "MemorySearchSummary"),
	"MemoryUpdateSummary": ("app.orchestration.models", "MemoryUpdateSummary"),
	"OrchestrationCapabilitiesResult": ("app.orchestration.capabilities", "OrchestrationCapabilitiesResult"),
	"OrchestrationCancelledError": ("app.orchestration.errors", "OrchestrationCancelledError"),
	"OrchestrationDependencyUnavailableError": ("app.orchestration.errors", "OrchestrationDependencyUnavailableError"),
	"OrchestrationDisabledError": ("app.orchestration.errors", "OrchestrationDisabledError"),
	"OrchestrationError": ("app.orchestration.errors", "OrchestrationError"),
	"OrchestrationErrorDetail": ("app.orchestration.errors", "OrchestrationErrorDetail"),
	"OrchestrationHealthResult": ("app.orchestration.health", "OrchestrationHealthResult"),
	"OrchestrationLimitExceededError": ("app.orchestration.errors", "OrchestrationLimitExceededError"),
	"OrchestrationLimitTracker": ("app.orchestration.limits", "OrchestrationLimitTracker"),
	"OrchestrationMalformedOutputError": ("app.orchestration.errors", "OrchestrationMalformedOutputError"),
	"OrchestrationRequest": ("app.orchestration.models", "OrchestrationRequest"),
	"OrchestrationResult": ("app.orchestration.models", "OrchestrationResult"),
	"OrchestrationRuntime": ("app.orchestration.core", "OrchestrationRuntime"),
	"OrchestrationRuntimeContext": ("app.orchestration.models", "OrchestrationRuntimeContext"),
	"OrchestrationStepSummary": ("app.orchestration.models", "OrchestrationStepSummary"),
	"OrchestrationStreamEvent": ("app.orchestration.events", "OrchestrationStreamEvent"),
	"OrchestrationTimeoutError": ("app.orchestration.errors", "OrchestrationTimeoutError"),
	"OrchestrationUseCaseCapability": ("app.orchestration.capabilities", "OrchestrationUseCaseCapability"),
	"StrategyDisabledError": ("app.orchestration.errors", "StrategyDisabledError"),
	"StrategyNotFoundError": ("app.orchestration.errors", "StrategyNotFoundError"),
	"StrategyPolicyDeniedError": ("app.orchestration.errors", "StrategyPolicyDeniedError"),
	"ToolCallSummary": ("app.orchestration.models", "ToolCallSummary"),
	"UnknownUseCaseError": ("app.orchestration.errors", "UnknownUseCaseError"),
	"WorkflowStateDelta": ("app.orchestration.state_delta", "WorkflowStateDelta"),
	"WorkflowStateSnapshot": ("app.orchestration.state_delta", "WorkflowStateSnapshot"),
	"apply_workflow_state_delta": ("app.orchestration.state_delta", "apply_workflow_state_delta"),
	"build_orchestration_request": ("app.orchestration.context", "build_orchestration_request"),
	"build_orchestration_result": ("app.orchestration.result_builder", "build_orchestration_result"),
	"build_runtime_context": ("app.orchestration.context", "build_runtime_context"),
	"build_workflow_state_snapshot": ("app.orchestration.context", "build_workflow_state_snapshot"),
	"build_workflow_state_snapshot_from_document": ("app.orchestration.context", "build_workflow_state_snapshot_from_document"),
	"error_detail_from_exception": ("app.orchestration.errors", "error_detail_from_exception"),
	"normalize_orchestration_error": ("app.orchestration.errors", "normalize_orchestration_error"),
	"orchestration_result_from_contract": ("app.orchestration.result_builder", "orchestration_result_from_contract"),
	"orchestration_result_to_contract": ("app.orchestration.result_builder", "orchestration_result_to_contract"),
	"sanitize_metadata": ("app.orchestration.models", "sanitize_metadata"),
	"workflow_state_delta_to_dict": ("app.orchestration.state_delta", "workflow_state_delta_to_dict"),
	"workflow_state_snapshot_from_document": ("app.orchestration.state_delta", "workflow_state_snapshot_from_document"),
	"workflow_state_snapshot_from_record": ("app.orchestration.state_delta", "workflow_state_snapshot_from_record"),
}


def __getattr__(name: str) -> Any:
	if name not in _LAZY_EXPORTS:
		raise AttributeError(name)
	module_name, attribute_name = _LAZY_EXPORTS[name]
	module = import_module(module_name)
	return getattr(module, attribute_name)

__all__ = [
	"AgentExecutionError",
	"AgentNotFoundError",
	"CitationSummary",
	"ConversationMessage",
	"DefaultOrchestrationRuntime",
	"DirectAgentOrchestrationRuntime",
	"EchoOrchestrationRuntime",
	"MemorySearchSummary",
	"MemoryUpdateSummary",
	"OrchestrationCapabilitiesResult",
	"OrchestrationCancelledError",
	"OrchestrationDependencyUnavailableError",
	"OrchestrationDisabledError",
	"OrchestrationError",
	"OrchestrationErrorDetail",
	"OrchestrationHealthResult",
	"OrchestrationLimitTracker",
	"OrchestrationLimitExceededError",
	"OrchestrationMalformedOutputError",
	"OrchestrationRequest",
	"OrchestrationResult",
	"OrchestrationRuntime",
	"OrchestrationRuntimeContext",
	"OrchestrationStepSummary",
	"OrchestrationStreamEvent",
	"OrchestrationTimeoutError",
	"OrchestrationUseCaseCapability",
	"StrategyDisabledError",
	"StrategyNotFoundError",
	"StrategyPolicyDeniedError",
	"ToolCallSummary",
	"UnknownUseCaseError",
	"WorkflowStateDelta",
	"WorkflowStateSnapshot",
	"apply_workflow_state_delta",
	"build_orchestration_request",
	"build_orchestration_result",
	"build_runtime_context",
	"build_workflow_state_snapshot",
	"build_workflow_state_snapshot_from_document",
	"error_detail_from_exception",
	"normalize_orchestration_error",
	"orchestration_result_from_contract",
	"orchestration_result_to_contract",
	"sanitize_metadata",
	"workflow_state_delta_to_dict",
	"workflow_state_snapshot_from_document",
	"workflow_state_snapshot_from_record",
]
