"""Structured agent-layer package introduced during backend agent migration."""

from __future__ import annotations

from importlib import import_module
from typing import Any


_LAZY_EXPORTS = {
    "AgentCancelledError": ("app.agents.errors", "AgentCancelledError"),
    "AgentCapabilities": ("app.agents.models", "AgentCapabilities"),
    "AgentCapabilityError": ("app.agents.errors", "AgentCapabilityError"),
    "AgentConfigurationError": ("app.agents.errors", "AgentConfigurationError"),
    "AgentDescriptor": ("app.agents.models", "AgentDescriptor"),
    "AgentDisabledError": ("app.agents.errors", "AgentDisabledError"),
    "AgentError": ("app.agents.errors", "AgentError"),
    "AgentErrorDetail": ("app.agents.errors", "AgentErrorDetail"),
    "AgentHandle": ("app.agents.base", "AgentHandle"),
    "AgentHealthResult": ("app.agents.models", "AgentHealthResult"),
    "AgentInputValidationError": ("app.agents.errors", "AgentInputValidationError"),
    "AgentLLMError": ("app.agents.errors", "AgentLLMError"),
    "AgentLimitExceededError": ("app.agents.errors", "AgentLimitExceededError"),
    "AgentMemoryCandidateError": ("app.agents.errors", "AgentMemoryCandidateError"),
    "AgentNotFoundError": ("app.agents.errors", "AgentNotFoundError"),
    "AgentOutputFormat": ("app.agents.models", "AgentOutputFormat"),
    "AgentOutputItem": ("app.agents.models", "AgentOutputItem"),
    "AgentOutputParseError": ("app.agents.errors", "AgentOutputParseError"),
    "AgentPolicyDeniedError": ("app.agents.errors", "AgentPolicyDeniedError"),
    "AgentPromptBuildError": ("app.agents.errors", "AgentPromptBuildError"),
    "AgentReviewError": ("app.agents.errors", "AgentReviewError"),
    "AgentReviewResult": ("app.agents.models", "AgentReviewResult"),
    "AgentRunRequest": ("app.agents.models", "AgentRunRequest"),
    "AgentRunResult": ("app.agents.models", "AgentRunResult"),
    "AgentStreamEvent": ("app.agents.models", "AgentStreamEvent"),
    "AgentStreamEventType": ("app.agents.models", "AgentStreamEventType"),
    "AgentTask": ("app.agents.models", "AgentTask"),
    "AgentToolIntentError": ("app.agents.errors", "AgentToolIntentError"),
    "AgentType": ("app.agents.models", "AgentType"),
    "AgentUsageSummary": ("app.agents.models", "AgentUsageSummary"),
    "AgentWarning": ("app.agents.models", "AgentWarning"),
    "BaseLlmAgent": ("app.agents.plugins.base_llm_agent", "BaseLlmAgent"),
    "GeneralAssistantAgent": ("app.agents.plugins.general_assistant", "GeneralAssistantAgent"),
    "LegacyCompatibleAgent": ("app.agents.base", "LegacyCompatibleAgent"),
    "MemoryCuratorAgent": ("app.agents.plugins.memory_curator", "MemoryCuratorAgent"),
    "ProjectAgent": ("app.agents.plugins.project_agent", "ProjectAgent"),
    "PromptContextItem": ("app.agents.models", "PromptContextItem"),
    "ReviewerAgent": ("app.agents.plugins.reviewer", "ReviewerAgent"),
    "ToolContextItem": ("app.agents.models", "ToolContextItem"),
    "agent_error_from_detail": ("app.agents.errors", "agent_error_from_detail"),
    "build_cancelled_event": ("app.agents.stream_mapping", "build_cancelled_event"),
    "build_completed_event": ("app.agents.stream_mapping", "build_completed_event"),
    "build_descriptor_trace_summary": ("app.agents.trace_helpers", "build_descriptor_trace_summary"),
    "build_error_trace_summary": ("app.agents.trace_helpers", "build_error_trace_summary"),
    "build_failed_event": ("app.agents.stream_mapping", "build_failed_event"),
    "build_health_trace_summary": ("app.agents.trace_helpers", "build_health_trace_summary"),
    "build_llm_trace_summary": ("app.agents.trace_helpers", "build_llm_trace_summary"),
    "build_memory_candidate_trace_summary": ("app.agents.trace_helpers", "build_memory_candidate_trace_summary"),
    "build_policy_scope": ("app.agents.policy", "build_policy_scope"),
    "build_prompt_messages": ("app.agents.prompts", "build_prompt_messages"),
    "build_prompt_sections": ("app.agents.prompts", "build_prompt_sections"),
    "build_prompt_trace_summary": ("app.agents.trace_helpers", "build_prompt_trace_summary"),
    "build_request_trace_summary": ("app.agents.trace_helpers", "build_request_trace_summary"),
    "build_result_trace_summary": ("app.agents.trace_helpers", "build_result_trace_summary"),
    "build_review_trace_summary": ("app.agents.trace_helpers", "build_review_trace_summary"),
    "build_run_request_from_context": ("app.agents.result_builder", "build_run_request_from_context"),
    "build_run_result": ("app.agents.result_builder", "build_run_result"),
    "build_started_event": ("app.agents.stream_mapping", "build_started_event"),
    "build_usage_summary": ("app.agents.result_builder", "build_usage_summary"),
    "capabilities_from_settings": ("app.agents.capabilities", "capabilities_from_settings"),
    "capability_labels": ("app.agents.capabilities", "capability_labels"),
    "capability_summary": ("app.agents.capabilities", "capability_summary"),
    "error_detail_from_exception": ("app.agents.errors", "error_detail_from_exception"),
    "from_legacy_agent_result": ("app.agents.result_builder", "from_legacy_agent_result"),
    "map_llm_stream_event": ("app.agents.stream_mapping", "map_llm_stream_event"),
    "memory_required": ("app.agents.capabilities", "memory_required"),
    "normalize_agent_error": ("app.agents.errors", "normalize_agent_error"),
    "render_output_format": ("app.agents.prompts", "render_output_format"),
    "render_task": ("app.agents.prompts", "render_task"),
    "require_capability": ("app.agents.capabilities", "require_capability"),
    "require_capability_allowed": ("app.agents.policy", "require_capability_allowed"),
    "require_policy_action": ("app.agents.policy", "require_policy_action"),
    "require_project_scope": ("app.agents.policy", "require_project_scope"),
    "resolve_system_prompt": ("app.agents.prompts", "resolve_system_prompt"),
    "streaming_supported": ("app.agents.capabilities", "streaming_supported"),
    "to_legacy_agent_result": ("app.agents.result_builder", "to_legacy_agent_result"),
    "tools_required": ("app.agents.capabilities", "tools_required"),
    "validate_capabilities": ("app.agents.capabilities", "validate_capabilities"),
}


def __getattr__(name: str) -> Any:
    if name not in _LAZY_EXPORTS:
        raise AttributeError(name)
    module_name, attribute_name = _LAZY_EXPORTS[name]
    module = import_module(module_name)
    return getattr(module, attribute_name)

__all__ = [
    "AgentCancelledError",
    "AgentCapabilities",
    "AgentCapabilityError",
    "AgentConfigurationError",
    "AgentDescriptor",
    "AgentDisabledError",
    "AgentError",
    "AgentErrorDetail",
    "AgentHandle",
    "AgentHealthResult",
    "AgentInputValidationError",
    "AgentLLMError",
    "AgentLimitExceededError",
    "AgentMemoryCandidateError",
    "AgentNotFoundError",
    "AgentOutputFormat",
    "AgentOutputItem",
    "AgentOutputParseError",
    "AgentPolicyDeniedError",
    "AgentPromptBuildError",
    "AgentReviewError",
    "AgentReviewResult",
    "AgentRunRequest",
    "AgentRunResult",
    "AgentStreamEvent",
    "AgentStreamEventType",
    "AgentTask",
    "AgentToolIntentError",
    "AgentType",
    "AgentUsageSummary",
    "AgentWarning",
    "BaseLlmAgent",
    "GeneralAssistantAgent",
    "MemoryCuratorAgent",
    "ProjectAgent",
    "ReviewerAgent",
    "LegacyCompatibleAgent",
    "PromptContextItem",
    "ToolContextItem",
    "agent_error_from_detail",
    "build_cancelled_event",
    "build_completed_event",
    "build_descriptor_trace_summary",
    "build_error_trace_summary",
    "build_failed_event",
    "build_health_trace_summary",
    "build_llm_trace_summary",
    "build_memory_candidate_trace_summary",
    "build_prompt_trace_summary",
    "build_policy_scope",
    "build_prompt_messages",
    "build_prompt_sections",
    "build_request_trace_summary",
    "build_result_trace_summary",
    "build_review_trace_summary",
    "build_run_request_from_context",
    "build_run_result",
    "build_usage_summary",
    "build_started_event",
    "capabilities_from_settings",
    "capability_labels",
    "capability_summary",
    "error_detail_from_exception",
    "from_legacy_agent_result",
    "map_llm_stream_event",
    "memory_required",
    "normalize_agent_error",
    "render_output_format",
    "render_task",
    "resolve_system_prompt",
    "require_capability",
    "require_capability_allowed",
    "require_policy_action",
    "require_project_scope",
    "streaming_supported",
    "to_legacy_agent_result",
    "tools_required",
    "validate_capabilities",
]